name: Java CI with Maven and SonarCloud

on:
  push:
    branches:
      - fix/**           # Ejecutar acciones en cada push a las ramas 'fix/...'

jobs:
  build:
    runs-on: ubuntu-latest # Ejecutar el pipeline en un entorno Ubuntu

    steps:
      # 1. Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar JDK 1.8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Usar la distribución Temurin del JDK
          java-version: '8'       # Especificar Java 8

      # 3. Instalar Maven y compilar el proyecto
      - name: Build with Maven
        run: mvn clean install

      # 4. Verificar la compilación sin ejecutar tests (opcional)
      - name: Verify build (skip tests)
        run: mvn clean compile -DskipTests

      # 5. Configurar SonarCloud
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: .   # Directorio base del proyecto
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

