name: Java CI with Maven

on:
  push:
    branches:
      - develop # Ejecutar acciones en cada push a la rama 'develop'
  pull_request:
    branches:
      - develop # Ejecutar acciones al crear o actualizar un pull request a 'develop'

jobs:
  build:
    runs-on: ubuntu-latest # Ejecutar el pipeline en un entorno Ubuntu

    steps:
      # Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar JDK 1.8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Usar la distribución Temurin del JDK
          java-version: '8'       # Especificar Java 8

      # Instalar Maven y compilar el proyecto
      - name: Build with Maven
        run: mvn clean install

      # Opcional: Verificar la compilación sin ejecutar tests
      - name: Verify build (skip tests)
        run: mvn clean compile -DskipTests
